/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.forms;

/**
 *
 * @author Stephen Fallis
 */
public class SelMain extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public SelMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testLabel = new javax.swing.JLabel();
        testPreviewLabel = new javax.swing.JLabel();
        siteLabel = new javax.swing.JLabel();
        browserLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        testList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        testPreviewArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        siteList = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        browserList = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        consoleTextField = new javax.swing.JTextArea();
        editTestButton = new javax.swing.JButton();
        specialCommandLabel = new javax.swing.JLabel();
        screenshotCheckbox = new javax.swing.JCheckBox();
        validateHTMLCheckbox = new javax.swing.JCheckBox();
        validateCSSCheckbox = new javax.swing.JCheckBox();
        selStatusLabel = new javax.swing.JLabel();
        startTestButton = new javax.swing.JButton();
        selStartButton = new javax.swing.JToggleButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        testDirMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        quitMenuItem = new javax.swing.JMenuItem();
        toolMenu = new javax.swing.JMenu();
        setSiteFileMenuItem = new javax.swing.JMenuItem();
        setTestDirMenuItem = new javax.swing.JMenuItem();
        setBrowserFileMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        specialCommandsPropertiesMenuItem = new javax.swing.JMenuItem();
        selPropertiesMenuItem = new javax.swing.JMenuItem();
        systemPropertiesMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        openSpecialDirMenuItem = new javax.swing.JMenuItem();
        openSelLogMenuItem = new javax.swing.JMenuItem();
        testMenu = new javax.swing.JMenu();
        addPasswordMenuItem = new javax.swing.JMenuItem();
        editTestMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        testLabel.setText("Tests");

        testPreviewLabel.setText("Test Preview");

        siteLabel.setText("Sites");

        browserLabel.setText("Browsers");

        testList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(testList);

        testPreviewArea.setColumns(20);
        testPreviewArea.setRows(5);
        jScrollPane2.setViewportView(testPreviewArea);

        siteList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(siteList);

        browserList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(browserList);

        consoleTextField.setColumns(20);
        consoleTextField.setRows(5);
        jScrollPane5.setViewportView(consoleTextField);

        editTestButton.setText("Edit Test");
        editTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTestButtonActionPerformed(evt);
            }
        });

        specialCommandLabel.setText("Special Commands");

        screenshotCheckbox.setText("Screenshots");
        screenshotCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenshotCheckboxActionPerformed(evt);
            }
        });

        validateHTMLCheckbox.setText("Validate HTML");
        validateHTMLCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateHTMLCheckboxActionPerformed(evt);
            }
        });

        validateCSSCheckbox.setText("Validate CSS");
        validateCSSCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateCSSCheckboxActionPerformed(evt);
            }
        });

        selStatusLabel.setText("Selenium RC Status + Site");

        startTestButton.setText("Start Test");

        selStartButton.setText("Selenium Start");

        fileMenu.setText("File");

        testDirMenuItem.setText("Open Test Directory");
        testDirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testDirMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(testDirMenuItem);
        fileMenu.add(jSeparator2);

        quitMenuItem.setText("Quit");
        quitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(quitMenuItem);

        menuBar.add(fileMenu);

        toolMenu.setText("Tools");

        setSiteFileMenuItem.setText("Set Site File");
        setSiteFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSiteFileMenuItemActionPerformed(evt);
            }
        });
        toolMenu.add(setSiteFileMenuItem);

        setTestDirMenuItem.setText("Set Test Directory");
        setTestDirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTestDirMenuItemActionPerformed(evt);
            }
        });
        toolMenu.add(setTestDirMenuItem);

        setBrowserFileMenuItem.setText("Set Browser File");
        setBrowserFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBrowserFileMenuItemActionPerformed(evt);
            }
        });
        toolMenu.add(setBrowserFileMenuItem);
        toolMenu.add(jSeparator1);

        specialCommandsPropertiesMenuItem.setText("Special Command Properties");
        specialCommandsPropertiesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialCommandsPropertiesMenuItemActionPerformed(evt);
            }
        });
        toolMenu.add(specialCommandsPropertiesMenuItem);

        selPropertiesMenuItem.setText("Selenium Properties");
        selPropertiesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selPropertiesMenuItemActionPerformed(evt);
            }
        });
        toolMenu.add(selPropertiesMenuItem);

        systemPropertiesMenuItem.setText("System Properties");
        systemPropertiesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemPropertiesMenuItemActionPerformed(evt);
            }
        });
        toolMenu.add(systemPropertiesMenuItem);

        menuBar.add(toolMenu);

        viewMenu.setText("View");

        openSpecialDirMenuItem.setText("Open Special Directory");
        openSpecialDirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSpecialDirMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(openSpecialDirMenuItem);

        openSelLogMenuItem.setText("View Selenium Directory");
        openSelLogMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSelLogMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(openSelLogMenuItem);

        menuBar.add(viewMenu);

        testMenu.setText("Test");

        addPasswordMenuItem.setText("Add Password");
        addPasswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPasswordMenuItemActionPerformed(evt);
            }
        });
        testMenu.add(addPasswordMenuItem);

        editTestMenuItem.setText("Edit Test");
        editTestMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTestMenuItemActionPerformed(evt);
            }
        });
        testMenu.add(editTestMenuItem);

        menuBar.add(testMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(testLabel)
                .addGap(186, 186, 186)
                .addComponent(testPreviewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siteLabel)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(editTestButton)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(startTestButton))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(browserLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(specialCommandLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(validateHTMLCheckbox)
                                            .addComponent(screenshotCheckbox)
                                            .addComponent(validateCSSCheckbox))))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(selStartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testLabel)
                    .addComponent(testPreviewLabel)
                    .addComponent(siteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editTestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(specialCommandLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(screenshotCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validateHTMLCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validateCSSCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startTestButton))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selStatusLabel)
                    .addComponent(selStartButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testDirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testDirMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testDirMenuItemActionPerformed

    private void openSelLogMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSelLogMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openSelLogMenuItemActionPerformed

    private void addPasswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPasswordMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPasswordMenuItemActionPerformed

    private void editTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTestButtonActionPerformed

    private void screenshotCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenshotCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_screenshotCheckboxActionPerformed

    private void validateHTMLCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateHTMLCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validateHTMLCheckboxActionPerformed

    private void validateCSSCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateCSSCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validateCSSCheckboxActionPerformed

    private void openSpecialDirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSpecialDirMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openSpecialDirMenuItemActionPerformed

    private void quitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuItemActionPerformed
    	//At the moment just want to dispose of the object when quit
    	//XXX Will need to add checks to ensure everything is closed.
    	this.dispose( );
    }//GEN-LAST:event_quitMenuItemActionPerformed

    private void setSiteFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSiteFileMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setSiteFileMenuItemActionPerformed

    private void setTestDirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTestDirMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setTestDirMenuItemActionPerformed

    private void setBrowserFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBrowserFileMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setBrowserFileMenuItemActionPerformed

    private void specialCommandsPropertiesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialCommandsPropertiesMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialCommandsPropertiesMenuItemActionPerformed

    private void selPropertiesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selPropertiesMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selPropertiesMenuItemActionPerformed

    private void systemPropertiesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemPropertiesMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_systemPropertiesMenuItemActionPerformed

    private void editTestMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTestMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTestMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SelMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addPasswordMenuItem;
    private javax.swing.JLabel browserLabel;
    private javax.swing.JList browserList;
    private javax.swing.JTextArea consoleTextField;
    private javax.swing.JButton editTestButton;
    private javax.swing.JMenuItem editTestMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openSelLogMenuItem;
    private javax.swing.JMenuItem openSpecialDirMenuItem;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JCheckBox screenshotCheckbox;
    private javax.swing.JMenuItem selPropertiesMenuItem;
    private javax.swing.JToggleButton selStartButton;
    private javax.swing.JLabel selStatusLabel;
    private javax.swing.JMenuItem setBrowserFileMenuItem;
    private javax.swing.JMenuItem setSiteFileMenuItem;
    private javax.swing.JMenuItem setTestDirMenuItem;
    private javax.swing.JLabel siteLabel;
    private javax.swing.JList siteList;
    private javax.swing.JLabel specialCommandLabel;
    private javax.swing.JMenuItem specialCommandsPropertiesMenuItem;
    private javax.swing.JButton startTestButton;
    private javax.swing.JMenuItem systemPropertiesMenuItem;
    private javax.swing.JMenuItem testDirMenuItem;
    private javax.swing.JLabel testLabel;
    private javax.swing.JList testList;
    private javax.swing.JMenu testMenu;
    private javax.swing.JTextArea testPreviewArea;
    private javax.swing.JLabel testPreviewLabel;
    private javax.swing.JMenu toolMenu;
    private javax.swing.JCheckBox validateCSSCheckbox;
    private javax.swing.JCheckBox validateHTMLCheckbox;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
