package com.hardcodeshit;

import java.io.IOException;

import com.core.Browser;
import com.core.Screenshot;
import com.thoughtworks.selenium.DefaultSelenium;

public class DurhamTest {

  private DefaultSelenium selenium;
  private String name, type, directory;
  private boolean first;
  private Screenshot sc;

  public void setUp( Browser browser ) {
    name = browser.getName( );
    type = browser.getType( );
    directory = browser.getScreenshotDirectory( );
    selenium = new DefaultSelenium( browser.getServerIP( ), 4444, "*" + type + " " + browser.getFileLocation( ),
        "https://127.0.0.1/" );
    selenium.start( );
  }

  public void testNew( String site ) throws InterruptedException, IOException {
    while ( true ) {
      selenium.open( "/" );
      selenium.click( "id=becsStartCalculator" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "link=Calculator home" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=becsStartCalculator" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=MARITAL_STATUS_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=HOME_ABROAD_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=CHILDREN_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=DETAILS_STUDENT_YOU_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ADDRESS_CUSTODY_YOU_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.select( "name=$$MM$DETAILS_DOB_YOU", "label=January" );
      selenium.type( "name=$$YY$DETAILS_DOB_YOU", "1989" );
      selenium.select( "name=$$DD$DETAILS_DOB_YOU", "label=2" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=INCOME_SUPPORT_true" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=IS_DLA_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=IS_AA_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=BLIND_YOU_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=OTHER_ADULTS_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=TYPE_OF_HOME_11" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=RENT_CHARGES_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=RENT_FREQ_2" );
      selenium.type( "name=$$RENT_AMOUNT", "500" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=CA_CARER_YOU_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=CA_ENTITLED_YOU_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=CARER_NO_CA_YOU_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=WORK_SITUATION_YOU_1" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.type( "name=$$DETAILS_FIRST_NAME_YOU", "NAME" );
      selenium.type( "name=$$DETAILS_SURNAME_YOU", "SURNAME" );
      selenium.click( "id=DETAILS_TITLE_YOU_2" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=DETAILS_OTHER_NAMES_YOU_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=DETAILS_NIN_STATUS_YOU_1" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.type( "name=$$DETAILS_NIN_YOU", "AB123456C" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.type( "name=$$DETAILS_PHONE_YOU", "0123456789" );
      selenium.click( "id=DETAILS_PHONE_TYPE_YOU_4" );
      selenium.type( "name=$$DETAILS_EMAIL_YOU", "stephen@teamnetsol.com" );
      selenium.type( "name=$$DETAILS_EMAIL_CONFIRM_YOU", "stephen@teamnetsol.com" );
      selenium.click( "id=DETAILS_NATIONALITY_YOU_1" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=DETAILS_UK_RESIDENT_YOU_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.type( "name=$$ADDRESS_CLAIM_FLAT_NUMBER", "2" );
      selenium.type( "name=$$ADDRESS_CLAIM_HOUSE_NUMBER", "2" );
      selenium.type( "name=$$ADDRESS_CLAIM_STREET", "Street" );
      selenium.type( "name=$$ADDRESS_CLAIM_TOWN", "Town" );
      selenium.type( "name=$$ADDRESS_CLAIM_POSTCODE", "A1 1AA" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ADDRESS_HERE_NOW_YOU_1" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.type( "name=$$YY$ADDRESS_HOW_LONG_YOU", "2012" );
      selenium.select( "name=$$DD$ADDRESS_HOW_LONG_YOU", "label=1" );
      selenium.select( "name=$$MM$ADDRESS_HOW_LONG_YOU", "label=January" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.type( "name=$$ADDRESS_PREVIOUS_FLAT_NUMBER_YOU", "3" );
      selenium.type( "name=$$ADDRESS_PREVIOUS_HOUSE_NUMBER_YOU", "3" );
      selenium.type( "name=$$ADDRESS_PREVIOUS_STREET_YOU", "Street" );
      selenium.type( "name=$$ADDRESS_PREVIOUS_TOWN_YOU", "City" );
      selenium.type( "name=$$ADDRESS_PREVIOUS_POSTCODE_YOU", "B1 1BB" );
      selenium.select( "name=$$DD$ADDRESS_PREVIOUS_DATE_YOU", "label=5" );
      selenium.select( "name=$$MM$ADDRESS_PREVIOUS_DATE_YOU", "label=September" );
      selenium.type( "name=$$YY$ADDRESS_PREVIOUS_DATE_YOU", "2012" );
      selenium.select( "name=$$MM$ADDRESS_PREVIOUS_DATE_YOU", "label=March" );
      selenium.click( "id=ADDRESS_PREVIOUS_TENANCY_TYPE_YOU_4" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ADDRESS_TEMP_AWAY_YOU_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ADDRESS_BUSINESS_YOU_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ADDRESS_OTHER_MAIN_HOME_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ADDRESS_HB_BEFORE_YOU_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ACCOMMODATION_TYPE_1" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ACCOMMODATION_TYPE_HOUSE_1" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ACCOMMODATION_GENERAL_DETAILS_HEATING_false" );
      selenium.click( "id=ACCOMMODATION_GENERAL_DETAILS_GARDEN_false" );
      selenium.click( "id=ACCOMMODATION_GENERAL_DETAILS_GARAGE_false" );
      selenium.click( "id=ACCOMMODATION_GENERAL_DETAILS_PARKING_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.type( "name=$$ACCOMMODATION_TOTAL_FLOORS", "2" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ACCOMMODATION_SHARE_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.type( "name=$$ACCOMMODATION_HOUSEHOLD_ROOMS_LIVING", "2" );
      selenium.type( "name=$$ACCOMMODATION_HOUSEHOLD_ROOMS_BEDSITTING", "2" );
      selenium.type( "name=$$ACCOMMODATION_HOUSEHOLD_ROOMS_BEDROOMS", "2" );
      selenium.type( "name=$$ACCOMMODATION_HOUSEHOLD_ROOMS_BATHROOMS", "2" );
      selenium.type( "name=$$ACCOMMODATION_HOUSEHOLD_ROOMS_TOILETS", "2" );
      selenium.type( "name=$$ACCOMMODATION_HOUSEHOLD_ROOMS_KITCHENS", "2" );
      selenium.type( "name=$$ACCOMMODATION_HOUSEHOLD_ROOMS_OTHER", "2" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.type( "name=$$ACCOMMODATION_LANDLORDS_NAME", "LANDLORD" );
      selenium.type( "name=$$ACCOMMODATION_LANDLORD_FLAT_NUMBER", "2" );
      selenium.type( "name=$$ACCOMMODATION_LANDLORD_HOUSE_NUMBER", "2" );
      selenium.type( "name=$$ACCOMMODATION_LANDLORD_STREET", "2" );
      selenium.type( "name=$$ACCOMMODATION_LANDLORD_TOWN", "2" );
      selenium.type( "name=$$ACCOMMODATION_LANDLORD_POSTCODE", "C1 1CC" );
      selenium.click( "id=ACCOMMODATION_LANDLORD_AGENT_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ACCOMMODATION_LANDLORD_RELATED_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.type( "name=$$YY$ACCOMMODATION_TENANCY_START_RENTING", "2012" );
      selenium.select( "name=$$MM$ACCOMMODATION_TENANCY_START_RENTING", "label=March" );
      selenium.select( "name=$$DD$ACCOMMODATION_TENANCY_START_RENTING", "label=2" );
      selenium.select( "name=$$DD$ACCOMMODATION_TENANCY_START", "label=9" );
      selenium.select( "name=$$MM$ACCOMMODATION_TENANCY_START", "label=February" );
      selenium.type( "name=$$YY$ACCOMMODATION_TENANCY_START", "2012" );
      selenium.click( "id=ACCOMMODATION_TENANCY_END_KNOWN_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ACCOMMODATION_TENANCY_TYPE_FURNISHED_1" );
      selenium.click( "id=ACCOMMODATION_TENANCY_TYPE_1" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=ACCOMMODATION_PREVIOUSLY_OWNED_HOME_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=RENT_CT_CHANGED_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=RENT_CT_INCREASE_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=RENT_CT_BEHIND_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=RENT_CT_FAIR_RENT_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=RENT_CT_OTHER_CHARGES_12" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=RENT_CT_SERVICE_CHARGES_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=OTHER_ADULTS_CUSTODY_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=EMPLOYMENT_OTHER_WORK_YOU_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.type( "name=$$YY$BENEFITS_IS_WHEN", "2012" );
      selenium.select( "name=$$MM$BENEFITS_IS_WHEN", "label=February" );
      selenium.select( "name=$$DD$BENEFITS_IS_WHEN", "label=2" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=OTHER_INFORMATION_TAKE_UP_6" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=OTHER_INFORMATION_YOU_CLAIMING_1" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=GETTING_BENEFIT_METHOD_5" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=GETTING_BENEFIT_BACKDATE_false" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "name=TNBnextButton" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "//input[@value='Proceed']" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "id=submit_method_print_and_send" );
      selenium.type( "id=postal_address_email", "stephen@teamnetsol.com" );
      selenium.type( "id=postal_address_email_check", "stephen@teamnetsol.com" );
      selenium.click( "name=post_submission_options" );
      selenium.waitForPageToLoad( "30000" );
      selenium.click( "link=Go to calculator home" );
    }
  }

  public void close( ) throws Exception {
    selenium.stop( );
  }
}
